# -*- coding: utf-8 -*-
"""pyalgo_알고리즘 베스트10 문제풀이.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14o94nJAKCvZvWIADJCofgjEmXGick0Mt
"""

# 1번

def solution(data):
    result = ''
    for d in data:
        result += chr(int(d.replace(" ","").replace("+", "1").replace("-", "0"),2))
    return result

# 2번
import re
def solution(data):
    days = re.findall('([r,e,v])(10|[0-9])',data)
    day = 0
    print(days)
    for i, j in days:
        day += int(j)
    print(day)
    return f'{day//10}월 {day%10}일'
solution('a10b9r1ce33uab8wc918v2cv11v9')