# -*- coding: utf-8 -*-
"""pyalgo_알고리즘 베스트10 문제풀이.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14o94nJAKCvZvWIADJCofgjEmXGick0Mt
"""

# 1번

def solution(data):
    result = ''
    for d in data:
        result += chr(int(d.replace(" ","").replace("+", "1").replace("-", "0"),2))
    return result