SELECT FLAVOR
FROM(
    SELECT A.FLAVOR, A.TOTAL_ORDER + J.TOTAL_ORDER TOTAL_ORDER
    FROM FIRST_HALF A JOIN JULY J 
    ON A.FLAVOR = J.FLAVOR
) TOTAL
    
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3